name: Deploy to Google Cloud Storage

on:
  push:
    branches: [ main ]

env:
  BUCKET_NAME: my-website-demo-oleg
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure bucket for website hosting
      run: |
        echo " Configuring bucket for website hosting..."
        gsutil web set -m index.html -e 404.html gs://$BUCKET_NAME
        gsutil uniformbucketlevelaccess set off gs://$BUCKET_NAME
        gsutil iam ch allUsers:objectViewer gs://$BUCKET_NAME

    - name: Deploy files to GCS
      run: |
        echo "Deploying files to bucket: $BUCKET_NAME"
        
        # Загружаем все файлы
        gcloud storage cp --recursive ./ gs://$BUCKET_NAME/
        
        # Устанавливаем правильные Content-Type для HTML файлов
        gcloud storage objects update gs://$BUCKET_NAME/*.html --content-type="text/html; charset=utf-8"
        
        echo " Files deployed successfully!"

    - name: Verify deployment
      run: |
        echo " Checking deployed files:"
        gcloud storage ls gs://$BUCKET_NAME/ --recursive
        
        echo "Website is available at:"
        echo "http://$BUCKET_NAME.storage.googleapis.com"

        